model_config:
  model_id: "unsloth/Qwen3-8B"
  max_seq_length: 2048
  load_in_4bit: false
  load_in_8bit: true

lora_config:
  r: 16
  lora_alpha: 16
  lora_dropout: 0
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: false

training_config:
  dataset_name: "Akhil-Theerthala/Kuvera-PersonalFinance-V2.1"
  dataset_num_samples: 6000
  test_size: 0.05
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  num_train_epochs: 1
  learning_rate: 0.0002
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407
  output_dir: "outputs"
  save_steps: 20
  save_total_limit: 2
  evaluation_strategy: "steps"
  eval_steps: 20
