version: '3.8'

services:
  vllm-server:
    image: vllm/vllm-openai:latest
    container_name: vllm_qwen_deployment
    ports:
      - "8000:8000"
    volumes:
      - ../model/qwen_awq_4bit:/model
    ipc: host
    shm_size: '4gb'
    environment:
      - VLLM_TORCH_COMPILE_LEVEL=0
    command: >
      --model /model
      --host 0.0.0.0
      --port 8000
      --trust-remote-code
      --quantization awq_marlin
      --dtype float16
      --gpu-memory-utilization 0.90
      --max-model-len 4096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
